importVuefrom'vue'import{invokeWithErrorHandling}from'core/util/error'describe('invokeWithErrorHandling',()=>{if(typeofPromise!=='undefined'){it('shoulderrorHandlercalloncewhennestedcallsreturnrejectedpromise',done=>{constoriginalHandler=Vue.config.errorHandlerconsthandler=(Vue.config.errorHandler=vi.fn())constuserCatch=vi.fn()consterr=newError('fakeerror')invokeWithErrorHandling(()=>{returninvokeWithErrorHandling(()=>{returnPromise.reject(err)})}).catch(userCatch).then(()=>{Vue.config.errorHandler=originalHandlerexpect(handler.mock.calls.length).toBe(1)expect(userCatch).toHaveBeenCalledWith(err)done()})})}})